### ISSUE TITLE
do you have plan support  godot 4.0?

### ISSUE THREAD

**Issue by iusn** [WolfBearGames/Godot-GeolocationPlugin-iOS#2]
do you have plan support  godot 4.0?

**Comment by WolfBearGames** [comment]
I planned to bring the plugin to Godot 4, but I wanted to wait until Godot 4 C# projects can be exported to iOS, because I mainly use C# in Godot.
Additionally the official iOS Godot Plugins are currently not supported in Godot 4, because the maintainer is no longer active. So I am not sure the plugin can be compiled for Godot 4 (I‘m using the official iOS plugins as a template).

I might have a look at compiling the plugin for Godot 4 late October when I have some time to spare, but no guarantees.

**Comment by iusn** [comment]
hello，I have build your plugin for godot 4, it is work. the official iOS Godot Plugins are currently supported in Godot 4 with gdscript in master line,(you need yourself build it)

**Comment by iusn** [comment]
Close issue

**Comment by WolfBearGames** [comment]
I don't know how you did that.
I tired to build for Godot 4 but I need the Godot 4 extracted headers. I tried to compile Godot 4.2 to generate the headers, but the compilation had an error. 
I used what was there and tried to compile the Plugin with the Godot 4.2 (incomplete?) files/headers and only got error like "error: no member named 'REAL' in 'Variant' [2]
     ADD_SIGNAL(MethodInfo("log", PropertyInfo(Variant::STRING, "message"), PropertyInfo(Variant::REAL, "number")));"

So... I don't know if it is possible to compile the plugin for Godot 4, at least with my limited level of knowledge and patience...
